// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: friend_list.proto

package web

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FriendListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *FriendListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FriendListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FriendListRequestMultiError, or nil if none found.
func (m *FriendListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FriendListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return FriendListRequestMultiError(errors)
	}

	return nil
}

// FriendListRequestMultiError is an error wrapping multiple validation errors
// returned by FriendListRequest.ValidateAll() if the designated constraints
// aren't met.
type FriendListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FriendListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FriendListRequestMultiError) AllErrors() []error { return m }

// FriendListRequestValidationError is the validation error returned by
// FriendListRequest.Validate if the designated constraints aren't met.
type FriendListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FriendListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FriendListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FriendListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FriendListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FriendListRequestValidationError) ErrorName() string {
	return "FriendListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FriendListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFriendListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FriendListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FriendListRequestValidationError{}

// Validate checks the field values on FriendListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FriendListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FriendListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FriendListResponseMultiError, or nil if none found.
func (m *FriendListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FriendListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FriendListResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FriendListResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FriendListResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FriendListResponseMultiError(errors)
	}

	return nil
}

// FriendListResponseMultiError is an error wrapping multiple validation errors
// returned by FriendListResponse.ValidateAll() if the designated constraints
// aren't met.
type FriendListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FriendListResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FriendListResponseMultiError) AllErrors() []error { return m }

// FriendListResponseValidationError is the validation error returned by
// FriendListResponse.Validate if the designated constraints aren't met.
type FriendListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FriendListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FriendListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FriendListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FriendListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FriendListResponseValidationError) ErrorName() string {
	return "FriendListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FriendListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFriendListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FriendListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FriendListResponseValidationError{}

// Validate checks the field values on FriendListResponse_Item with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FriendListResponse_Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FriendListResponse_Item with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FriendListResponse_ItemMultiError, or nil if none found.
func (m *FriendListResponse_Item) ValidateAll() error {
	return m.validate(true)
}

func (m *FriendListResponse_Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for NickName

	// no validation rules for Avatar

	// no validation rules for Gender

	if len(errors) > 0 {
		return FriendListResponse_ItemMultiError(errors)
	}

	return nil
}

// FriendListResponse_ItemMultiError is an error wrapping multiple validation
// errors returned by FriendListResponse_Item.ValidateAll() if the designated
// constraints aren't met.
type FriendListResponse_ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FriendListResponse_ItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FriendListResponse_ItemMultiError) AllErrors() []error { return m }

// FriendListResponse_ItemValidationError is the validation error returned by
// FriendListResponse_Item.Validate if the designated constraints aren't met.
type FriendListResponse_ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FriendListResponse_ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FriendListResponse_ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FriendListResponse_ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FriendListResponse_ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FriendListResponse_ItemValidationError) ErrorName() string {
	return "FriendListResponse_ItemValidationError"
}

// Error satisfies the builtin error interface
func (e FriendListResponse_ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFriendListResponse_Item.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FriendListResponse_ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FriendListResponse_ItemValidationError{}
