// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"love_knot/internal/app"
	"love_knot/internal/app/api"
	"love_knot/internal/app/api/handler"
	"love_knot/internal/app/api/handler/web"
	"love_knot/internal/app/api/handler/web/v1"
	"love_knot/internal/app/api/router"
	service2 "love_knot/internal/app/service"
	"love_knot/internal/app/service/web/v1"
	"love_knot/internal/app/storage/cache"
	"love_knot/internal/app/storage/repo"
	"love_knot/internal/config"
	"love_knot/internal/job"
	"love_knot/internal/provider"
)

// Injectors from wire.go:

func NewHttpInjector(conf *config.Config) *api.AppProvider {
	client := provider.NewRedisClient(conf)
	emailStorage := cache.NewEmailStorage(client)
	db := provider.NewMysqlClient(conf)
	userRepo := repo.NewUsers(db)
	templateService := &service.TemplateService{}
	emailClient := provider.NewEmailClient(conf)
	emailService := &service.EmailService{
		Storage:  emailStorage,
		UserRepo: userRepo,
		Template: templateService,
		Client:   emailClient,
	}
	common := &v1.Common{
		EmailService: emailService,
	}
	userService := &service.UserService{
		UserRepo: userRepo,
	}
	source := repo.NewSource(db, client)
	httpClient := provider.NewHttpClient()
	requestClient := provider.NewRequestClient(httpClient)
	ipAddressService := &service.IpAddressService{
		Source: source,
		Config: conf,
		Client: requestClient,
	}
	deviceRepo := repo.NewDevice(db)
	deviceService := &service.DeviceService{
		DeviceRepo: deviceRepo,
	}
	user := &v1.User{
		Config:           conf,
		UserService:      userService,
		EmailService:     emailService,
		IpAddressService: ipAddressService,
		DeviceService:    deviceService,
	}
	webV1 := &web.V1{
		Common: common,
		User:   user,
	}
	webHandler := &web.Handler{
		V1: webV1,
	}
	handlerHandler := &handler.Handler{
		Web: webHandler,
	}
	engine := router.NewRouter(conf, handlerHandler)
	appProvider := &api.AppProvider{
		Config: conf,
		Engine: engine,
	}
	return appProvider
}

func NewSQLInjector(conf *config.Config) *job.SQLProvider {
	db := provider.NewMysqlClient(conf)
	sqlProvider := &job.SQLProvider{
		Config: conf,
		DB:     db,
	}
	return sqlProvider
}

// wire.go:

var providerSet = wire.NewSet(provider.NewHttpClient, provider.NewRequestClient, provider.NewMysqlClient, provider.NewRedisClient, provider.NewEmailClient, service2.ProviderSet, app.CacheProviderSet, app.RepoProviderSet)
