// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"love_knot/internal/app/api"
	"love_knot/internal/app/api/router"
	"love_knot/internal/config"
	"love_knot/internal/job"
	"love_knot/internal/provider"
)

// Injectors from wire.go:

func NewHttpInjector(conf *config.Config) *api.AppProvider {
	engine := router.NewRouter(conf)
	appProvider := &api.AppProvider{
		Config: conf,
		Engine: engine,
	}
	return appProvider
}

func NewSQLInjector(conf *config.Config) *job.SQLProvider {
	gormDB := provider.NewMysqlClient(conf)
	sqlProvider := &job.SQLProvider{
		Config: conf,
		DB:     gormDB,
	}
	return sqlProvider
}

// wire.go:

var providerSet = wire.NewSet(provider.NewHttpClient, provider.NewRequestClient, provider.NewMysqlClient)
