// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common.proto

package web

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SendEmailCodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendEmailCodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendEmailCodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendEmailCodeRequestMultiError, or nil if none found.
func (m *SendEmailCodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendEmailCodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Email

	// no validation rules for Channel

	if len(errors) > 0 {
		return SendEmailCodeRequestMultiError(errors)
	}

	return nil
}

// SendEmailCodeRequestMultiError is an error wrapping multiple validation
// errors returned by SendEmailCodeRequest.ValidateAll() if the designated
// constraints aren't met.
type SendEmailCodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendEmailCodeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendEmailCodeRequestMultiError) AllErrors() []error { return m }

// SendEmailCodeRequestValidationError is the validation error returned by
// SendEmailCodeRequest.Validate if the designated constraints aren't met.
type SendEmailCodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendEmailCodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendEmailCodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendEmailCodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendEmailCodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendEmailCodeRequestValidationError) ErrorName() string {
	return "SendEmailCodeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendEmailCodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendEmailCodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendEmailCodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendEmailCodeRequestValidationError{}

// Validate checks the field values on SendEmailCodeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendEmailCodeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendEmailCodeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendEmailCodeResponseMultiError, or nil if none found.
func (m *SendEmailCodeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendEmailCodeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SendEmailCodeResponseMultiError(errors)
	}

	return nil
}

// SendEmailCodeResponseMultiError is an error wrapping multiple validation
// errors returned by SendEmailCodeResponse.ValidateAll() if the designated
// constraints aren't met.
type SendEmailCodeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendEmailCodeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendEmailCodeResponseMultiError) AllErrors() []error { return m }

// SendEmailCodeResponseValidationError is the validation error returned by
// SendEmailCodeResponse.Validate if the designated constraints aren't met.
type SendEmailCodeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendEmailCodeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendEmailCodeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendEmailCodeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendEmailCodeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendEmailCodeResponseValidationError) ErrorName() string {
	return "SendEmailCodeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendEmailCodeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendEmailCodeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendEmailCodeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendEmailCodeResponseValidationError{}
